/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import entity.Customer;
import entity.Employee;
import entity.Invoice_detail;
import entity.Invoices;
import entity.Product;
import handlers.Customer_DAO;
import handlers.Invoices_DAO;
import handlers.Invoicesdetail_DAO;
import interfaces.CheckoutInterface;
import interfaces.orderInterface;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author KHONG TAM
 */
public class FromThanhToan extends javax.swing.JFrame {

    private Employee emp1;
    private DefaultTableModel model2;
    private CheckoutInterface checkout;
    private orderInterface listener;

    public void openForm(String id, String tenKH, String sdtKH, DefaultTableModel model, double total, Employee emp, CheckoutInterface check) {
        if (jlTenKH != null) {
            jlTenKH.setText(tenKH);
        }
        this.checkout = check;
        this.model2 = model;
        jlSDT.setText(sdtKH);
        LocalDateTime currentDate = LocalDateTime.now();
        String formattedTime = currentDate.format(DateTimeFormatter.ofPattern("yyyy-MM-dd-HH-mm-ss"));
        this.emp1 = emp;
        jlNgaytao.setText(formattedTime);
        jTable2.setModel(model);
        jTable2.removeColumn(jTable2.getColumnModel().getColumn(5));
        DecimalFormat df = new DecimalFormat("#,###.00VND");

        jlTongtien.setText(df.format(total));
        jlTienthanhtoan.setText(df.format(total));

    }

    /**
     * Creates new form FromThanhToan
     */
    public FromThanhToan(orderInterface listener) {
        initComponents();
        this.listener = listener;
    }

//    private FromThanhToan(Employee emp) {
//        this.emp1=emp;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlTenKH = new javax.swing.JLabel();
        jlSDT = new javax.swing.JLabel();
        jlNgaytao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jlTongtien = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jlTienthanhtoan = new javax.swing.JLabel();
        jlCheckout = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtGhichu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("THÔNG TIN KHÁCH HÀNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("TÊN KHÁCH HÀNG");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 150, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("SỐ ĐIỆN THOẠI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("NGÀY TẠO HD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, -1));

        jlTenKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlTenKH.setForeground(new java.awt.Color(153, 51, 0));
        jlTenKH.setText("jlTenKH");
        jPanel1.add(jlTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 200, -1));

        jlSDT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlSDT.setForeground(new java.awt.Color(153, 51, 0));
        jlSDT.setText("jlSDT");
        jPanel1.add(jlSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 190, -1));

        jlNgaytao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlNgaytao.setForeground(new java.awt.Color(153, 51, 0));
        jlNgaytao.setText("Ngày tạo");
        jPanel1.add(jlNgaytao, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 190, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 204, 102));
        jScrollPane2.setForeground(new java.awt.Color(153, 51, 0));
        jScrollPane2.setToolTipText("");

        jTable2.setBackground(new java.awt.Color(255, 204, 102));
        jTable2.setForeground(new java.awt.Color(153, 51, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Tên sản phẩm", "Giá", "Số lượng", "Thành tiền"
            }
        ));
        jTable2.setSelectionBackground(new java.awt.Color(255, 204, 102));
        jTable2.setSelectionForeground(new java.awt.Color(153, 51, 0));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 440, 190));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("TỔNG TIỀN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 110, -1));

        jlTongtien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlTongtien.setForeground(new java.awt.Color(153, 51, 0));
        jPanel1.add(jlTongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 130, 20));

        jPanel2.setBackground(new java.awt.Color(153, 51, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(370, 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 450, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("SỐ TIỀN THANH TOÁN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 160, -1));

        jlTienthanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlTienthanhtoan.setForeground(new java.awt.Color(153, 51, 0));
        jPanel1.add(jlTienthanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 130, 20));

        jlCheckout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCheckout.setForeground(new java.awt.Color(153, 51, 0));
        jlCheckout.setText("CHECKOUT");
        jlCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCheckoutMouseClicked(evt);
            }
        });
        jPanel1.add(jlCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 0));
        jLabel9.setText("CLOSE");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 40, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("GHI CHÚ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jtGhichu.setBackground(new java.awt.Color(255, 204, 102));
        jtGhichu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtGhichu.setForeground(new java.awt.Color(153, 51, 0));
        jtGhichu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtGhichuActionPerformed(evt);
            }
        });
        jPanel1.add(jtGhichu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 340, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private String createIDHD() {
        LocalDateTime currentTime = LocalDateTime.now();
        String formattedTime = currentTime.format(DateTimeFormatter.ofPattern("yyMMddHHmmss"));
        return "HD" + formattedTime;
    }

    private void jlCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCheckoutMouseClicked
        String id = createIDHD();
        String description = jtGhichu.getText();
        Customer_DAO dao = new Customer_DAO();
        String sdt = jlSDT.getText();
        String cusID = dao.getCustomer(sdt).getId();
        // thêm id nhân viên sau khi tạo đăng nhập thành công
        String empID = emp1.getId();
        LocalDate create_at = LocalDate.now();
        Invoices inv = new Invoices(id, create_at, new Employee(empID), new Customer(cusID), description);
        Invoices_DAO invoidao = new Invoices_DAO();
        // thêm hóa đơn trước
        invoidao.addInvoices(inv);
        // thêm từng chi tiết hóa đơn
        Invoicesdetail_DAO detai = new Invoicesdetail_DAO();
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            String invoiID = id;
            String prodID = (String) jTable2.getValueAt(i, 0);
            int qty = (int) jTable2.getValueAt(i, 3);
            detai.addInvoiceDetail(new Invoice_detail(new Product(prodID), qty, new Invoices(invoiID)));
        }
        this.listener.reloadOrder();

        model2.setRowCount(0);
        inHoaDon();
        
        checkout.onCheckout();
        setVisible(false);
    }//GEN-LAST:event_jlCheckoutMouseClicked

    private void jtGhichuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtGhichuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtGhichuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                Employee emp1=new Employee();
//                new FromThanhToan(emp1).setVisible(true);
            }
        });
    }

    private void inHoaDon() {
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Hóa đơn");

        printerJob.setPrintable(new Printable() {
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2d = (Graphics2D) graphics;
                g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
                // In nội dung hóa đơn ở đây
                jPanel1.printAll(graphics);

                return Printable.PAGE_EXISTS;
            }
        });

        boolean doPrint = printerJob.printDialog();
        if (doPrint) {
            try {
                printerJob.print();
            } catch (PrinterException e) {
                e.printStackTrace();
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel jlCheckout;
    private javax.swing.JLabel jlNgaytao;
    private javax.swing.JLabel jlSDT;
    private javax.swing.JLabel jlTenKH;
    private javax.swing.JLabel jlTienthanhtoan;
    private javax.swing.JLabel jlTongtien;
    private javax.swing.JTextField jtGhichu;
    // End of variables declaration//GEN-END:variables
}
