/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import entity.Product;
import handlers.productControllers;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
//import javax.swing.Im;


/**
 *
 * @author hgmin
 */
public class Home extends javax.swing.JPanel {
ImageIcon leftIcon;
Image leftImg;
 public productControllers connection;
    /**
     * Creates new form Home
     */
    public Home() {
        connection = new productControllers();
        
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        JbCoffee = new javax.swing.JButton();
        jbDaxay = new javax.swing.JButton();
        jbTra = new javax.swing.JButton();
        jbSoda = new javax.swing.JButton();
        jbKhac = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jbBanh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jscCafe = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jsDaxay = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jscTra = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jscSoda = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jscKhac = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jscBanh = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();

        jButton9.setBackground(new java.awt.Color(255, 204, 255));
        jButton9.setText("jButton6");
        jButton9.setPreferredSize(new java.awt.Dimension(75, 32));

        panelMain.setBackground(new java.awt.Color(255, 255, 204));
        panelMain.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cart");

        phoneTxt.setBackground(new java.awt.Color(255, 255, 204));
        phoneTxt.setText("Phone");
        phoneTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        phoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTxtActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(255, 255, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Huong", "Minh", "Tam", "Tung" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Index", "Product", "Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, 194, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelMain.add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setPreferredSize(new java.awt.Dimension(696, 527));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(102, 51, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel3.setPreferredSize(new java.awt.Dimension(696, 90));

        JbCoffee.setBackground(new java.awt.Color(204, 102, 0));
        JbCoffee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JbCoffee.setForeground(new java.awt.Color(255, 204, 51));
        JbCoffee.setText("Coffee");
        JbCoffee.setMaximumSize(new java.awt.Dimension(100, 50));
        JbCoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JbCoffeeMouseClicked(evt);
            }
        });

        jbDaxay.setBackground(new java.awt.Color(204, 102, 0));
        jbDaxay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbDaxay.setForeground(new java.awt.Color(255, 204, 51));
        jbDaxay.setText("Đá xay");
        jbDaxay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbDaxayMouseClicked(evt);
            }
        });
        jbDaxay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDaxayActionPerformed(evt);
            }
        });

        jbTra.setBackground(new java.awt.Color(204, 102, 0));
        jbTra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbTra.setForeground(new java.awt.Color(255, 204, 51));
        jbTra.setText("Trà");
        jbTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbTraMouseClicked(evt);
            }
        });
        jbTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTraActionPerformed(evt);
            }
        });

        jbSoda.setBackground(new java.awt.Color(204, 102, 0));
        jbSoda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbSoda.setForeground(new java.awt.Color(255, 204, 51));
        jbSoda.setText("Soda");
        jbSoda.setPreferredSize(new java.awt.Dimension(75, 30));
        jbSoda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSodaMouseClicked(evt);
            }
        });

        jbKhac.setBackground(new java.awt.Color(204, 102, 0));
        jbKhac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbKhac.setForeground(new java.awt.Color(255, 204, 51));
        jbKhac.setText("Thức uống khác");
        jbKhac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbKhacMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 51));
        jLabel5.setText("Menu");

        jbBanh.setBackground(new java.awt.Color(204, 102, 0));
        jbBanh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbBanh.setForeground(new java.awt.Color(255, 204, 51));
        jbBanh.setText("Bánh");
        jbBanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbBanhMouseClicked(evt);
            }
        });
        jbBanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBanhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(JbCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jbDaxay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jbTra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jbSoda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jbBanh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbKhac)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbDaxay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbSoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBanh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JbCoffee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel4.setPreferredSize(new java.awt.Dimension(696, 437));
        try {
            ArrayList<Product> products = connection.getListHome();
            for (Product product : products) {
                System.out.print(1);
                ProductPanel productPanel = new ProductPanel(product);
                jPanel4.add(productPanel);
            }

        }catch( Exception e){

        }
        jPanel4.setLayout(new javax.swing.OverlayLayout(jPanel4));

        jscCafe.setPreferredSize(new java.awt.Dimension(696, 437));

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(696, 437));
        jPanel5.setLayout(new java.awt.GridLayout(2, 3, 15, 15));
        jscCafe.setViewportView(jPanel5);

        jPanel4.add(jscCafe);

        jsDaxay.setPreferredSize(new java.awt.Dimension(696, 437));

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));
        jPanel6.setPreferredSize(new java.awt.Dimension(696, 437));
        jPanel6.setLayout(new java.awt.GridLayout(2, 3, 15, 15));
        jsDaxay.setViewportView(jPanel6);

        jPanel4.add(jsDaxay);

        jscTra.setPreferredSize(new java.awt.Dimension(696, 437));

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setPreferredSize(new java.awt.Dimension(696, 437));
        jPanel7.setLayout(new java.awt.GridLayout(2, 3, 15, 15));
        jscTra.setViewportView(jPanel7);

        jPanel4.add(jscTra);

        jscSoda.setPreferredSize(new java.awt.Dimension(696, 437));

        jPanel8.setBackground(new java.awt.Color(102, 204, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(696, 437));
        jPanel8.setLayout(new java.awt.GridLayout(2, 3, 5, 15));
        jscSoda.setViewportView(jPanel8);

        jPanel4.add(jscSoda);

        jscKhac.setPreferredSize(new java.awt.Dimension(696, 437));

        jPanel9.setBackground(new java.awt.Color(102, 102, 0));
        jPanel9.setPreferredSize(new java.awt.Dimension(696, 437));
        jPanel9.setLayout(new java.awt.GridLayout(2, 3, 15, 15));
        jscKhac.setViewportView(jPanel9);

        jPanel4.add(jscKhac);

        jscBanh.setPreferredSize(new java.awt.Dimension(696, 437));

        jPanel10.setBackground(new java.awt.Color(102, 51, 0));
        jPanel10.setPreferredSize(new java.awt.Dimension(696, 437));
        jPanel10.setLayout(new java.awt.GridLayout(2, 3, 15, 15));
        jscBanh.setViewportView(jPanel10);

        jPanel4.add(jscBanh);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        panelMain.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void phoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTxtActionPerformed

    private void jbDaxayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDaxayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbDaxayActionPerformed

    private void jbTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbTraActionPerformed

    private void jbBanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbBanhActionPerformed

    private void JbCoffeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JbCoffeeMouseClicked
        jscCafe.setVisible(true);
        jsDaxay.setVisible(false);
        jscTra.setVisible(false);
        jscSoda.setVisible(false);
        jscKhac.setVisible(false);
        jscBanh.setVisible(false);
    }//GEN-LAST:event_JbCoffeeMouseClicked

    private void jbDaxayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDaxayMouseClicked
        jscCafe.setVisible(false);
        jsDaxay.setVisible(true);
        jscTra.setVisible(false);
        jscSoda.setVisible(false);
        jscKhac.setVisible(false);
        jscBanh.setVisible(false);
    }//GEN-LAST:event_jbDaxayMouseClicked

    private void jbTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTraMouseClicked
         jscCafe.setVisible(false);
        jsDaxay.setVisible(false);
        jscTra.setVisible(true);
        jscSoda.setVisible(false);
        jscKhac.setVisible(false);
        jscBanh.setVisible(false);
    }//GEN-LAST:event_jbTraMouseClicked

    private void jbSodaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSodaMouseClicked
         jscCafe.setVisible(false);
        jsDaxay.setVisible(false);
        jscTra.setVisible(false);
        jscSoda.setVisible(true);
        jscKhac.setVisible(false);
        jscBanh.setVisible(false);
    }//GEN-LAST:event_jbSodaMouseClicked

    private void jbBanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBanhMouseClicked
        jscCafe.setVisible(false);
        jsDaxay.setVisible(false);
        jscTra.setVisible(false);
        jscSoda.setVisible(false);
        jscKhac.setVisible(false);
        jscBanh.setVisible(true);
    }//GEN-LAST:event_jbBanhMouseClicked

    private void jbKhacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbKhacMouseClicked
         jscCafe.setVisible(false);
        jsDaxay.setVisible(false);
        jscTra.setVisible(false);
        jscSoda.setVisible(false);
        jscKhac.setVisible(true);
        jscBanh.setVisible(false);
    }//GEN-LAST:event_jbKhacMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbCoffee;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbBanh;
    private javax.swing.JButton jbDaxay;
    private javax.swing.JButton jbKhac;
    private javax.swing.JButton jbSoda;
    private javax.swing.JButton jbTra;
    private javax.swing.JScrollPane jsDaxay;
    private javax.swing.JScrollPane jscBanh;
    private javax.swing.JScrollPane jscCafe;
    private javax.swing.JScrollPane jscKhac;
    private javax.swing.JScrollPane jscSoda;
    private javax.swing.JScrollPane jscTra;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField phoneTxt;
    // End of variables declaration//GEN-END:variables

    private void setDefaultCloseOperation(int DO_NOTHING_ON_CLOSE) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
